### ISSUE TITLE
mxnet环境问题

### ISSUE THREAD

**Issue by playerben** [YimianDai/open-acm#1]
我在使用该代码时，首先按照readme中的步骤配置mxnet环境，详细操作为：pip install --upgrade mxnet-cu100 gluoncv，
相关版本为 mxnet：1.5.0，gluoncv：0.8.0
但在跑实验时遇到以下问题：
E:\Anaconda3\envs\zmj\python.exe "C:/Users/hp/Desktop/deep learning/open-acm-master/train_dentist.py"
Traceback (most recent call last):
  File "C:/Users/hp/Desktop/deep learning/open-acm-master/train_dentist.py", line 14, in <module>
    from gluoncv.utils import makedirs, LRScheduler, LRSequential
  File "E:\Anaconda3\envs\zmj\lib\site-packages\gluoncv\__init__.py", line 12, in <module>
    from . import data
  File "E:\Anaconda3\envs\zmj\lib\site-packages\gluoncv\data\__init__.py", line 31, in <module>
    from .kitti.kitti_dataset import KITTIRAWDataset, KITTIOdomDataset
  File "E:\Anaconda3\envs\zmj\lib\site-packages\gluoncv\data\kitti\__init__.py", line 2, in <module>
    from .kitti_dataset import *
  File "E:\Anaconda3\envs\zmj\lib\site-packages\gluoncv\data\kitti\kitti_dataset.py", line 21, in <module>
    from .kitti_utils import generate_depth_map
  File "E:\Anaconda3\envs\zmj\lib\site-packages\gluoncv\data\kitti\kitti_utils.py", line 12, in <module>
    from mxnet.util import is_np_array
ImportError: cannot import name 'is_np_array' from 'mxnet.util' (E:\Anaconda3\envs\zmj\lib\site-packages\mxnet\util.py)

Process finished with exit code 1

请问作者现在所用到的mxnet和gluoncv的版本是什么呢？谢谢作者对我的问题进行解答，不胜感激！

**Comment by YimianDai** [comment]
您好！我目前用的是 mxnet 1.7.0，gluoncv 0.8.0. 

您显示报错的代码应该都是 mxnet 和 gluoncv 调用的问题，我想您不一定跑 train_dentist.py 才会遇到这个问题，在您目前的环境下调用其他 API 应该也会有类似的问题，因为目前**您报错的信息出在加载 gluoncv 和 mxnet 上，是安装环境的问题，跟我的代码没有关系**。我没法复现您的问题，如果您升级到 1.7.0 后调用 GluonCV 和 MXnet 还有问题，那可能需要去 Gluon 论坛了。

最后，我刚刚测试了一下，`pip install --upgrade mxnet-cu100 gluoncv` 安装的是 **MXNet-1.7.0**，并不是您所说的 **MXNet-1.5.0**. 下面是截图证明

![image](https://user-images.githubusercontent.com/9448249/100315630-ecb86d00-2ff3-11eb-8d45-48905d3365e5.png)

在 MXNet 1.7.0 下调用 `from mxnet.util import is_np_array` 是没有问题的，下面是截图证明：

![image](https://user-images.githubusercontent.com/9448249/100316388-62710880-2ff5-11eb-85f7-2cb1384ba493.png)

我想这很可能是您那里报错的原因，应该可以破案了。

祝一切顺利！

**Comment by playerben** [comment]
问题解决了。之前我是用windows系统，导致配置的环境和您的环境不用。在我换成Ubuntu系统之后，按照上述方法，就配置成了和您一样的环境。感谢大佬！

**Comment by YimianDai** [comment]
解决了就好，祝您一切顺利！

这个 issue 我就 close 了。
